name: Sign and Release APK

on:
  workflow_dispatch:

jobs:
  sign_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Zip app-debug files
      run: |
        cd app-debug
        zip -r ../MifiService-unsig.zip .
        cd ..

    - name: Rename unsig.zip to unsig.apk
      run: mv MifiService-unsig.zip MifiService-unsig.apk

    - name: Sign the APK
      run: |
        java -jar ./gradle/apksigner.jar sign \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --ks-pass pass:${{ secrets.KEYS_PASSWORD }} \
          --ks keys/testkey.x509.pem \
          --out MifiService.apk \
          MifiService-unsig.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MifiService.apk
        path: MifiService.apk

    - name: Generate random release tag
      id: random_tag
      run: echo "RELEASE_TAG=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 6)" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: MifiService.apk
        tag_name: ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
